version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=challenge,challenge_test
    ports:
      - '5432:5432'
